# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
#- {icon: 'github', link: 'https://www.github.com/lenpaul'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'linkedin', link: 'http://www.linkedin.com/in/lenpaul/'}
- {icon: 'envelope', link: 'mailto:shinpatsu@outlook.com.vn'}
#- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Mới hơn'
  previous_page: 'Cũ hơn'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'Bạn cũng có thể thích:'

post_date_prefix: 'Đăng vào '
